name: Node CI

on: [push]

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install, build, and test
      run: |
        yarn install --frozen-lockfile
        yarn lint
        yarn build
        yarn test --coverage
        bash <(curl -s https://codecov.io/bash)
        echo ${{ github.ref }}
        echoh ${{ matrix['node-version'] }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: release
      if: github.ref == 'master' && matrix['node-version'] == '12.x'
      run: yarn release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
